config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#index"
  get 'homes/index'
  # get 'products/index'
  # get 'products/show'
  # get 'products/edit'
  # get 'products/new'
  
  resources :products
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
  validates :product_name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 15 }
  validates :price, presence: true
  validates :description, presence: true, length: { minimum: 8, maximum: 50 }
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @product = Product.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :new]
  before_action :find_product, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def create
    @product = current_user.products.build(products_params)
    if @product.save
      flash[:notice] = "Product has been successfully created 👍"
      redirect_to products_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @product = Product.update(products_params)
      flash[:notice] = "Product  successfully edited 👍"
      redirect_to products_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path
    flash[:notice] = "Product has been successfully deleted 💬"
  end

  private

  def find_product
    @product = Product.find(params[:id])
  end

  def products_params
    params.require(:product).permit(:product_name, :price, :description, :user_id)
  end

  def require_user
    if current_user != @product.user
      flash[:notice] = "Only user can edit or delete their article 🎭"
      redirect_to products_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/homes/index.html.erb
<center>
<% if user_signed_in? %>
<h2> You are logged in #{}.. So you can access the products  </h2>
  <%= button_to "Sign Out", destroy_user_session_path, method: :delete %>
  <%= button_to "Edit profile",edit_user_registration_path, method: :get %>
  <%= link_to "products", products_path %>
<% else %>
<h2> Please Sign up or Sign in for accessing the product </h2>
  <%= button_to "Signup", new_user_registration_path, method: :get %><br/>
  <%= button_to "Sign-in", user_session_path,method: :get %>
<% end %>
</center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTestingApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
  <div class="mt-3 mb-3">
  <center>
    <p class=" alert-success"  ><%= notice %></p>
    <p class=" alert-danger "><%= alert %></p>
    <% flash.each do |name, message| %>
    <% message %>
    <% end %>
  </center>
  </div>
    <div>
      <% if user_signed_in? %><br/>
      <h13>User login with email ID</h13><br/>
      <b><%= current_user.email %></b>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<div class="container mb-3 mt-3">
<div class="row justify-content-center">
<div class="col-7 mt-4">
<div class="card text-center shadow mb-5 bg-white" >
  <%= form_with model: @product do |form| %>
		<div>
			<%= form.label :product_name, style: "display: block" %>
			<%= form.text_field :product_name, class: "form-control shadow rounded", placeholder: "Enter a product_name" %>
		</div>

		<div>
			<%= form.label :price, style: "display: block" %>
			<%= form.number_field :price, class: "form-control shadow rounded", placeholder: "$$$$$$$$" %>
		</div>

		<div>
			<%= form.label :description, style: "display: block" %>
			<%= form.text_area :description, class: "form-control shadow rounded", placeholder: "Enter the description" %>
		</div>
		
		<div class="mb-3 mt-3">
			<%= form.submit class: "btn btn-outline-primary btn-md" %>
		</div> 
	<% end %>

app/views/products/edit.html.erb
<h1 class="text-center mt-3 mb-4">Edit you product</h1>
<%= render 'form' %>

app/views/products/index.html.erb
<div class="container mb-3 mt-3">
<div class="row justify-content-center">
<div class="col-9 mt-4">
<div class="card text-center shadow mb-5 bg-white">
<h2 class="text-center mb-3 mt-3", style="color:red;">List of all product</h2>
<center>
  <table>
      <th>Product Id</th>
      <th>Product name</th>
			<th colspan="3">Action</th>
			<% @products.each do |product| %>
    <tr>
      <td><%= product.id %></td>
			<td><%= product.product_name %></td>
			<td><%= button_to "Show",product_path(product.id),method: :get, class: "btn btn-outline-primary"%>
	  	<td><%= button_to "Edit",edit_product_path(product.id),method: :get, class: "btn btn-outline-success" %></td>
      <td><%= button_to "Delete",product_path(product.id),method: :delete, class: "btn btn-outline-danger" %></td>
    <% end %>
		</tr>
  </table>
</center>
<center>
  <div class="mb-3 mt-3"> 
   <b> <%= link_to "Add new product",new_product_path %></b>
  </div>
</center>
<center>
<div>
  <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-danger btn-sm" %>
</div>
</center>

app/views/products/new.html.erb
<h1 class="text-center mt-4 mb-4 ">Create a new product</h1>
<%= render 'form' %>

app/views/products/show.html.erb
<div class="col-lg-6 mx-lg-auto">
<div class="card shadow">
<div class="card-header">
<h2 class="card-title text-center", style="color:red;">Product Detials</h2>
<center>
  <div class="col-lg-7 mb-3 mt-3">
    <div class="card" >
      <div class="card-body">
        <th><b><u>Product Name:</u></b></th><br/>
        <td><%= @product.product_name %></th><br/>
        <th><b><u>Price:</u></b></th><br/>
        <td><%= @product.price %></th><br/>
        <th><b><u>Description:</u></th></b><br/>
        <td><%= @product.description %></th><br/>
      </div>
    </div>
  </div>
</center>
</div>
<center>
  <td><%= button_to "Back ", products_path(@product),method: :get, class:"btn btn-primary float-right mb-3 mt-3"  %></td
</center>